language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.5
  - 2.2.0
  - jruby-19mode
  - rbx-2.2.7
  - ruby-head
  - jruby-head
  - rbx-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-head
